# Generated by Django 3.0.5 on 2021-07-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_crud_app', '0002_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutimg', models.ImageField(upload_to='aboutImage/')),
                ('title', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
