# Generated by Django 3.0.5 on 2021-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_crud_app', '0003_aboutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
